#+TITLE: otm-notes
#+AUTHOR: codexog
#+EXPORT_FILE_NAME: README.md

* Use

This is a simple note taking application. One will eventually be able to take, edit, and remove notes using it,
notes can be tagged and filtered by tag. For more see [[./../master/docs/design.md][design]]. The application has a graphical as well as a command-line interface. The command line interface and the graphical interface are synchronised. In other words they modify the same global state. The graphical and command line interfaces can be terminated separately, they are, however, the same process. At the moment the application must be killed to terminate. The notes are stored in an edn file, for more on the format see [[https://github.com/edn-format/edn][edn-format]].

* Dev 

To use the development tools you will need to have clojure installed. See [[https://clojure.org/guides/getting_started][GettingStarted]] for instructions on installing and getting started. For more information on the command line tools see [[https://clojure.org/reference/deps_and_cli][Deps and CLI guide]]. For a brief overview of the code structure see [[./../master/docs/architecture.md][architecture]].

** Running the project 

#+BEGIN_SRC shell :export code
  clj -A:main "filename"
#+END_SRC

using a desired filename.

** Make a jar and uberjar
Using [[https://github.com/luchiniatwork/cambada][cambada]]

#+BEGIN_SRC shell
  clj -A:uberjar
#+END_SRC
The files are found in the [[./../master/target][target]] directory.

The standalone can be run using the command
#+BEGIN_SRC shell
  java -jar target/otm-notes-1.0.0-SNAPSHOT-standalone.jar "filename"
#+END_SRC
Here again using an actual filename.

** Start a pretty REPL
A repl enhanced by [[https://github.com/bhauman/rebel-readline][rebel-readline]]

#+BEGIN_SRC shell
  clj -A:repl
#+END_SRC

** Check your style
Check the project using [[https://github.com/borkdude/clj-kondo][clj-kondo]]

#+BEGIN_SRC shell
  clj -A:style
#+END_SRC

** Run tests
Run the test suite using [[https://github.com/lambdaisland/kaocha][kaocha]]
#+BEGIN_SRC shell
  clj -A:test
#+END_SRC

** Test coverage report
Using [[https://github.com/cloverage/cloverage/tree/master/cloverage/sample/cloverage/sample][cloverage]]

#+BEGIN_SRC shell
  clj -A:cov
#+END_SRC

* Bugs
- The cursor jumps around in the gui text-fields for tags.

* Misc
For the timelog of the project [[./../master/docs/timelog.org][timelog]].
